application:
  bindAddress: :8445
  production: false
  debug: false
database:
  address: localhost:3401
  name: portfolio
  username: bitfever
  password: bitfever
authentication:
  authority: https://bitfever-server:8443/auth/realms/bitfever
  clientId: bitfever-backend
  clientSecret: xyz
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
#scan:
#  address: https://158.69.26.216:8443/api/v1/strategies
#  periodHour: 2
