application:
  bindAddress: :8445
  production: false
  debug: false
database:
  address: localhost:3401
  name: portfolio
  username: bitfever
  password: bitfever
authentication:
  authority: https://bitfever-server:8443/auth/realms/bitfever
  clientId: bitfever-backend
  clientSecret: AXRNrPrBiiOlBcwiOPX67XFTcbu9p9IZ
platform:
  storage: https://bitfever-server:8452/api/storage
messaging:
  address: localhost:8450
  username: rabbit-admin
  password: rabbit.admin
